version: "3.7"

services:

  app:
    build: ./app
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb

  redis:
    hostname: redis
    image: "redis:5-alpine"
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  workers:
    build: './workers'
    user: nobody
    depends_on:
      - redis
      - app
      - mongodb